/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppDatasetsRouteImport } from './routes/app/datasets'
import { Route as AppDatasetsNewRouteImport } from './routes/app/datasets.new'
import { Route as AppDatasetsIdRouteImport } from './routes/app/datasets.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppDatasetsRoute = AppDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AppRoute,
} as any)
const AppDatasetsNewRoute = AppDatasetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppDatasetsRoute,
} as any)
const AppDatasetsIdRoute = AppDatasetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDatasetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/datasets': typeof AppDatasetsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/datasets/$id': typeof AppDatasetsIdRoute
  '/app/datasets/new': typeof AppDatasetsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/datasets': typeof AppDatasetsRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/datasets/$id': typeof AppDatasetsIdRoute
  '/app/datasets/new': typeof AppDatasetsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/datasets': typeof AppDatasetsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/datasets/$id': typeof AppDatasetsIdRoute
  '/app/datasets/new': typeof AppDatasetsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/datasets'
    | '/app/'
    | '/app/datasets/$id'
    | '/app/datasets/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/datasets'
    | '/app'
    | '/app/datasets/$id'
    | '/app/datasets/new'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/datasets'
    | '/app/'
    | '/app/datasets/$id'
    | '/app/datasets/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/datasets': {
      id: '/app/datasets'
      path: '/datasets'
      fullPath: '/app/datasets'
      preLoaderRoute: typeof AppDatasetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/datasets/new': {
      id: '/app/datasets/new'
      path: '/new'
      fullPath: '/app/datasets/new'
      preLoaderRoute: typeof AppDatasetsNewRouteImport
      parentRoute: typeof AppDatasetsRoute
    }
    '/app/datasets/$id': {
      id: '/app/datasets/$id'
      path: '/$id'
      fullPath: '/app/datasets/$id'
      preLoaderRoute: typeof AppDatasetsIdRouteImport
      parentRoute: typeof AppDatasetsRoute
    }
  }
}

interface AppDatasetsRouteChildren {
  AppDatasetsIdRoute: typeof AppDatasetsIdRoute
  AppDatasetsNewRoute: typeof AppDatasetsNewRoute
}

const AppDatasetsRouteChildren: AppDatasetsRouteChildren = {
  AppDatasetsIdRoute: AppDatasetsIdRoute,
  AppDatasetsNewRoute: AppDatasetsNewRoute,
}

const AppDatasetsRouteWithChildren = AppDatasetsRoute._addFileChildren(
  AppDatasetsRouteChildren,
)

interface AppRouteChildren {
  AppDatasetsRoute: typeof AppDatasetsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDatasetsRoute: AppDatasetsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
